### ISSUE TITLE
Unclear license

### ISSUE THREAD

**Issue by realdadfish** [rtyley/roboguice-sherlock#13]
Hi Roberto!

Thank you for this wonderful little helper. Could you please state / clarify the code's license somewhere?

Thanks!

**Comment by rtyley** [comment]
Hi @tommyd3mdi - the licence is Apache V2, which was hidden away in the pom.xml:

https://github.com/rtyley/roboguice-sherlock/blob/1dc921f/pom.xml#L22-26

...I've now added it as a LICENSE file as well.

RoboGuice and ActionBarSherlock are both licenced as Apache V2, so it makes sense for this library to have the same licence.

**Comment by realdadfish** [comment]
Thank you!
