### ISSUE TITLE
@ContentView can't work with requestWindowFeature()

### ISSUE THREAD

**Issue by zhen9ao** [rtyley/roboguice-sherlock#9]
Set `@ContentView(R.layout.xx)` before the Activity, and call `requestWindowFeature()` to get some ActionbarSherlock feature, then the app crashes with the following exception:

> Caused by: android.util.AndroidRuntimeException: requestFeature() must be called before adding content

**Comment by jonasfa** [comment]
You should call `requestWindowFeature()` before calling `super.onCreate(savedInstanceState)`.

**Comment by JakeWharton** [comment]
You may want to file this on [RoboGuice](http://code.google.com/p/roboguice/)'s issue list but @jonasfa's suggestion is the appropriate fix.

**Comment by zhen9ao** [comment]
Thanks! @jonasfa 's suggestion works, but it's wired to call `requestWindowFeature()` before `super.onCreate(savedInstanceState)`
